version: '3.8'

services :
    postgres:
      image: postgres
      container_name: postgres_compose
      environment:
        POSTGRES_USER: localhost
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_DB: postgres
      ports:
       - "5432:5432"
      volumes:
      - database_backup:/var/lib/postgresql/data

    backend:
    build:
      context: .
      dockerfile: Dockerfile   # make sure filename matches
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
volumes:
   database_backup:
